### ISSUE TITLE
Install Fails when using .zip of release

### ISSUE THREAD

**Issue by dinah03** [VERITAS-Observatory/gammapy-tools#47]
When using the .zip from the first release and the main repository produced by GitHub the following error happens when you run 
`pip install .`
```

Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "/Users/dinahibrahim/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/dinahibrahim/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/dinahibrahim/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 307, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 284, in __init__
          self.finalize_options()
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 659, in finalize_options
          ep(self)
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 123, in infer_version
          _assign_version(dist, config)
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 58, in _assign_version
          _version_missing(config)
        File "/private/var/folders/pt/j8wrlz9d48g9k5jhkp7vys600000gn/T/pip-build-env-ikr12fex/overlay/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 117, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /Users/dinahibrahim/Desktop/SUMMER 2024 RESEARCH/gammapy-tools-main.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by matthew-w-lundy** [comment]
Perhaps this is simply an issue of documentation but I sent the wrong thing to dinah by accident and it caused issues

**Comment by steob92** [comment]
I think this was fixed in 41b04df 

Can you try running with [1.1_rc](https://github.com/VERITAS-Observatory/gammapy-tools/tree/1.1_rc) for now? The real test will be on the next release.

**Comment by matthew-w-lundy** [comment]
Still fails:
```
pip install .
Processing /home/matthew/Downloads/gammapy-tools-1.1_rc
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "/home/matthew/anaconda3/envs/mamba/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/matthew/anaconda3/envs/mamba/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/matthew/anaconda3/envs/mamba/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 307, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 284, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 659, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 123, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 58, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-em1sacj2/overlay/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 117, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /home/matthew/Downloads/gammapy-tools-1.1_rc.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
```

The error occurs when you use the generate zip instead of git cloning

**Comment by steob92** [comment]
Can you show how you're getting 1.1_rc, are you downloading/checkout/switch? I can install in a fresh env, I get an issue with V2DL3 needing to be installed when running but that's unrelated:
```
(base) obriens•RAID1/VERITAS_Data/gammapy-tools-testing» git clone git@github.com:VERITAS-Observatory/gammapy-tools.git                                                            [11:24:26]
Cloning into 'gammapy-tools'...
remote: Enumerating objects: 730, done.
remote: Counting objects: 100% (322/322), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 730 (delta 207), reused 218 (delta 132), pack-reused 408
Receiving objects: 100% (730/730), 8.04 MiB | 11.52 MiB/s, done.
Resolving deltas: 100% (415/415), done.
(base) obriens•RAID1/VERITAS_Data/gammapy-tools-testing» cd gammapy-tools                                                                                                          [11:24:50]
(base) obriens•VERITAS_Data/gammapy-tools-testing/gammapy-tools(main)» git switch 1.1_rc                                                                                           [11:24:53]
Branch '1.1_rc' set up to track remote branch '1.1_rc' from 'origin'.
Switched to a new branch '1.1_rc'
(base) obriens•VERITAS_Data/gammapy-tools-testing/gammapy-tools(1.1_rc⚡)» mamba activate test                                                                                     [11:27:52]
(test) obriens•VERITAS_Data/gammapy-tools-testing/gammapy-tools(1.1_rc⚡)» pip install .                                                                                           [11:27:56]
Processing /raid/RAID1/VERITAS_Data/gammapy-tools-testing/gammapy-tools
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gammapy>=1.1 (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading gammapy-1.2.tar.gz (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 11.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pydantic (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading pydantic-2.7.1-py3-none-any.whl.metadata (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.3/107.3 kB 12.5 MB/s eta 0:00:00
Collecting scipy==1.11.4 (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached scipy-1.11.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting astropy (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading astropy-6.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting astroquery (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading astroquery-0.4.7-py3-none-any.whl.metadata (7.2 kB)
Collecting matplotlib (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading matplotlib-3.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting multiprocess (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting numpy (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting PyYAML (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting regions (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading regions-0.9-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting astropy (from gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading astropy-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)
Collecting click>=7.0 (from gammapy>=1.1->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting iminuit>=2.8.0 (from gammapy>=1.1->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached iminuit-2.25.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pyerfa>=2.0.1.1 (from astropy->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading pyerfa-2.0.1.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.7 kB)
Collecting astropy-iers-data>=0.2024.2.26.0.28.55 (from astropy->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading astropy_iers_data-0.2024.5.20.0.29.40-py3-none-any.whl.metadata (5.1 kB)
Collecting packaging>=19.0 (from astropy->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting contourpy>=1.0.1 (from matplotlib->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading contourpy-1.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading fonttools-4.51.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (159 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.5/159.5 kB 13.1 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached kiwisolver-1.4.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting pillow>=8 (from matplotlib->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading pillow-10.3.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.7 (from matplotlib->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting annotated-types>=0.4.0 (from pydantic->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.18.2 (from pydantic->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading pydantic_core-2.18.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in /home/obriens/mambaforge/envs/test/lib/python3.11/site-packages (from pydantic->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524) (4.11.0)
Collecting requests>=2.19 (from astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading requests-2.32.2-py3-none-any.whl.metadata (4.6 kB)
Collecting beautifulsoup4>=4.8 (from astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting html5lib>=0.999 (from astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting keyring>=15.0 (from astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading keyring-25.2.1-py3-none-any.whl.metadata (20 kB)
Collecting pyvo>=1.1 (from astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading pyvo-1.5.2-py3-none-any.whl.metadata (4.7 kB)
Collecting dill>=0.3.8 (from multiprocess->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting soupsieve>1.2 (from beautifulsoup4>=4.8->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: six>=1.9 in /home/obriens/mambaforge/envs/test/lib/python3.11/site-packages (from html5lib>=0.999->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524) (1.16.0)
Collecting webencodings (from html5lib>=0.999->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting jaraco.classes (from keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading jaraco.classes-3.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting jaraco.functools (from keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading jaraco.functools-4.0.1-py3-none-any.whl.metadata (2.9 kB)
Collecting jaraco.context (from keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading jaraco.context-5.3.0-py3-none-any.whl.metadata (4.0 kB)
Collecting importlib-metadata>=4.11.4 (from keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
Collecting SecretStorage>=3.2 (from keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading SecretStorage-3.3.3-py3-none-any.whl.metadata (4.0 kB)
Collecting jeepney>=0.4.2 (from keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading jeepney-0.8.0-py3-none-any.whl.metadata (1.3 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.19->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests>=2.19->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.19->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests>=2.19->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.11.4->keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading zipp-3.18.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=2.0 (from SecretStorage>=3.2->keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading cryptography-42.0.7-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting more-itertools (from jaraco.classes->keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached more_itertools-10.2.0-py3-none-any.whl.metadata (34 kB)
Collecting backports.tarfile (from jaraco.context->keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading backports.tarfile-1.1.1-py3-none-any.whl.metadata (2.0 kB)
Collecting cffi>=1.12 (from cryptography>=2.0->SecretStorage>=3.2->keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Using cached cffi-1.16.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=15.0->astroquery->gammapy_tools==1.0.1.dev11+gba7bd0a.d20240524)
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Using cached scipy-1.11.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.4 MB)
Downloading astropy-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 13.5 MB/s eta 0:00:00
Downloading matplotlib-3.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 13.4 MB/s eta 0:00:00
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Downloading pydantic-2.7.1-py3-none-any.whl (409 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.3/409.3 kB 12.9 MB/s eta 0:00:00
Downloading pydantic_core-2.18.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 13.5 MB/s eta 0:00:00
Using cached PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
Downloading regions-0.9-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (999 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 999.2/999.2 kB 13.1 MB/s eta 0:00:00
Downloading astroquery-0.4.7-py3-none-any.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 13.6 MB/s eta 0:00:00
Using cached multiprocess-0.70.16-py311-none-any.whl (143 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading astropy_iers_data-0.2024.5.20.0.29.40-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 13.5 MB/s eta 0:00:00
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Downloading contourpy-1.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (306 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 306.0/306.0 kB 13.9 MB/s eta 0:00:00
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached dill-0.3.8-py3-none-any.whl (116 kB)
Downloading fonttools-4.51.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 13.5 MB/s eta 0:00:00
Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached iminuit-2.25.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (426 kB)
Downloading keyring-25.2.1-py3-none-any.whl (38 kB)
Using cached kiwisolver-1.4.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
Using cached packaging-24.0-py3-none-any.whl (53 kB)
Downloading pillow-10.3.0-cp311-cp311-manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 13.6 MB/s eta 0:00:00
Downloading pyerfa-2.0.1.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 738.7/738.7 kB 13.5 MB/s eta 0:00:00
Downloading pyparsing-3.1.2-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 13.9 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 13.6 MB/s eta 0:00:00
Downloading pyvo-1.5.2-py3-none-any.whl (910 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 910.8/910.8 kB 13.3 MB/s eta 0:00:00
Downloading requests-2.32.2-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 kB 15.4 MB/s eta 0:00:00
Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 13.7 MB/s eta 0:00:00
Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
Downloading idna-3.7-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 11.2 MB/s eta 0:00:00
Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Using cached jeepney-0.8.0-py3-none-any.whl (48 kB)
Using cached SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 13.2 MB/s eta 0:00:00
Downloading jaraco.classes-3.4.0-py3-none-any.whl (6.8 kB)
Downloading jaraco.context-5.3.0-py3-none-any.whl (6.5 kB)
Downloading jaraco.functools-4.0.1-py3-none-any.whl (9.8 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Downloading cryptography-42.0.7-cp39-abi3-manylinux_2_28_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 13.6 MB/s eta 0:00:00
Downloading zipp-3.18.2-py3-none-any.whl (8.3 kB)
Downloading backports.tarfile-1.1.1-py3-none-any.whl (29 kB)
Using cached more_itertools-10.2.0-py3-none-any.whl (57 kB)
Using cached cffi-1.16.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (464 kB)
Downloading pycparser-2.22-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 11.9 MB/s eta 0:00:00
Building wheels for collected packages: gammapy_tools, gammapy
  Building wheel for gammapy_tools (pyproject.toml) ... done
  Created wheel for gammapy_tools: filename=gammapy_tools-1.0.1.dev11+gba7bd0a.d20240524-py3-none-any.whl size=2605963 sha256=5c3a75bbc5c611dbc22033c666ef17b51575fe66b3f4c82e3c0d20276744eca7
  Stored in directory: /home/obriens/.cache/pip/wheels/f0/30/38/b9e03c35ccad31bfd91b3c0372a632f4acd309151f6d36a42b
  Building wheel for gammapy (pyproject.toml) ... done
  Created wheel for gammapy: filename=gammapy-1.2-cp311-cp311-linux_x86_64.whl size=969372 sha256=43d9b019c737c0c7a4fc5e12f9eb243870ea8f89a1f08e24bf833ea86379eef4
  Stored in directory: /home/obriens/.cache/pip/wheels/17/fa/44/0a0c994b6947ac308e912e01cef2b63d3b0aa28771ba3e2206
Successfully built gammapy_tools gammapy
Installing collected packages: webencodings, zipp, urllib3, soupsieve, PyYAML, python-dateutil, pyparsing, pydantic-core, pycparser, pillow, packaging, numpy, more-itertools, kiwisolver, jeepney, idna, html5lib, fonttools, dill, cycler, click, charset-normalizer, certifi, backports.tarfile, astropy-iers-data, annotated-types, scipy, requests, pyerfa, pydantic, multiprocess, jaraco.functools, jaraco.context, jaraco.classes, importlib-metadata, iminuit, contourpy, cffi, beautifulsoup4, matplotlib, cryptography, astropy, SecretStorage, regions, pyvo, keyring, gammapy, astroquery, gammapy_tools
Successfully installed PyYAML-6.0.1 SecretStorage-3.3.3 annotated-types-0.7.0 astropy-6.0.1 astropy-iers-data-0.2024.5.20.0.29.40 astroquery-0.4.7 backports.tarfile-1.1.1 beautifulsoup4-4.12.3 certifi-2024.2.2 cffi-1.16.0 charset-normalizer-3.3.2 click-8.1.7 contourpy-1.2.1 cryptography-42.0.7 cycler-0.12.1 dill-0.3.8 fonttools-4.51.0 gammapy-1.2 gammapy_tools-1.0.1.dev11+gba7bd0a.d20240524 html5lib-1.1 idna-3.7 iminuit-2.25.2 importlib-metadata-7.1.0 jaraco.classes-3.4.0 jaraco.context-5.3.0 jaraco.functools-4.0.1 jeepney-0.8.0 keyring-25.2.1 kiwisolver-1.4.5 matplotlib-3.9.0 more-itertools-10.2.0 multiprocess-0.70.16 numpy-1.26.4 packaging-24.0 pillow-10.3.0 pycparser-2.22 pydantic-2.7.1 pydantic-core-2.18.2 pyerfa-2.0.1.4 pyparsing-3.1.2 python-dateutil-2.9.0.post0 pyvo-1.5.2 regions-0.9 requests-2.32.2 scipy-1.11.4 soupsieve-2.5 urllib3-2.2.1 webencodings-0.5.1 zipp-3.18.2


```

**Comment by steob92** [comment]
I see your comment on the zip now.

[Quick fix](https://github.com/pypa/setuptools_scm/issues/1011) solution:

```
cat > setup.py  << EOF
from setuptools import setup

setup(
    name='xxx',
    use_scm_version={
        'local_scheme': 'dirty-tag',
        'write_to': '_version.py',
        'fallback_version': '1.1.0',
    },
    setup_requires=['setuptools_scm'],
)
EOF
```

Then:
```
pip install .
```

Long term, need to look into more details. I'd prefer not to have to maintain multiple version files and locations.
